### ISSUE TITLE
[CI] Any Linter or Indent checker?

### ISSUE THREAD

**Issue by nrudesu** [GNUWeeb/GNUWeebBot#30]
One of contributor often forget about indentations rule.

So, I think we need CI for this project, but new problem occur. We need pick linter software is suitable and set it to our configuration or just make own indent checker

TODO :

- [x] Research about linter software
- [x] Make linter software + add some option alternative
- [x] ~Waiting for review~ or pick external lint software
- [ ] Then add it to CI

**Comment by ammarfaizi2** [comment]
I think we can write something up. It shouldn't be too hard for indentation checking.

Static analyzer with simple PHP or Python or Perl script could do this.

**Comment by nrudesu** [comment]
@Im-Fernanda confirm to me want to write it

**Comment by nrudesu** [comment]
So @Im-Fernanda , give us some detail about this

**Comment by Im-Fernanda** [comment]
i will tell you the details later when this actually works because i'm not completely sure if it can be used normally.

**Comment by nrudesu** [comment]
Okay fine, we will wait about this

**Comment by ammarfaizi2** [comment]
@nrudesu 
> Do you need another repository, or this repository is enough for you?

Create another branch on this repository is okay?
I can start to initialize and wire this part up of you want to.

**Comment by siarie** [comment]
Ok, so the most problem is about indentation?
Have you ever heard about [editorconfig](https://editorconfig.org/). It's not a linter anyway. 

The website says:

> EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs.

I use it a lot and it's enough to solve the problem (especially for indentation).

Having a linter will make it much better. But if you want a quick solution, maybe [editorconfig](https://editorconfig.org/) can be consideration.

**Comment by ammarfaizi2** [comment]
@siarie how would you integrate editorconfig with CI (GitHub Workflow)?

**Comment by ammarfaizi2** [comment]
I took a look at this https://github.com/editorconfig/editorconfig.github.com/pull/48
It seems to be GitHub web editor rather than static analysis in CI which will yield a failure message when wrong indentation is found.

**Comment by siarie** [comment]
> how would you integrate editorconfig with CI (GitHub Workflow)?

I don't know about CI stuff. I just use editorconfig on my editor/IDE.

If you looking for static analysis [check this out](https://github.com/cpplint/cpplint).

Another reference:
- [https://nvuillam.github.io/mega-linter/](https://nvuillam.github.io/mega-linter/)

**Comment by nrudesu** [comment]
> @Im-Fernanda confirm to me want to write it

@Im-Fernanda changes the mind, he want to use existing lint program, so I edited the issue descriptions and please tell us about ur idea 


>Create another branch on this repository is okay?
I can start to initialize and wire this part up if you want to.

Okay

> cpplint?

hmmm, thinking...

**Comment by Im-Fernanda** [comment]
>> @Im-Fernanda please tell us about ur idea
Previously i had an idea how to use flake8 but i thought it was too bloat because he needs a lot of pre requisites dependencies, but I think it is easier to integrate with CI.

reference https://flake8.pycqa.org/en/latest/

**Comment by Im-Fernanda** [comment]
>> @Im-Fernanda please tell us about ur idea
>
> Previously i had an idea how to use flake8 but i thought it was too bloat because he needs a lot of pre requisites dependencies, but I think it is easier to integrate with CI.
> 
> reference https://flake8.pycqa.org/en/latest/

**Comment by ammarfaizi2** [comment]
@Im-Fernanda can you try flake8 to examine current codebase and send me the output?
Would like to see how is the output compared to the cpplint.

**Comment by Im-Fernanda** [comment]
> @Im-Fernanda isn't flake8 for python?
> 
he linter for all languages not python only

**Comment by nrudesu** [comment]
> @Im-Fernanda changes the mind, he want to use existing lint program, so I edited the issue descriptions and @Im-Fernanda please tell us about ur idea

seriously, @Im-Fernanda makes me confuse, lmao. but finally he write his own linter. I already fork it.

https://github.com/GNUWeeb/linter-C
